pipeline {
   agent any
   
   

  stages {
   stage('checkout') {
     steps {
       checkout scm
     }

  }

  
  // do jest testing
    stage('test') {
      steps {
       sh 'yarn test'
     }
  }
   
  //publish to npm repo
  stage('publish') {
     steps {
      sh 'source ~/.profile'
      sh 'source ~/.bash_profile'
      sh 'npm publish'
     }

 }
     
 } 
}

