pipeline {
   agent any
   
   

  stages {
   stage('checkout') {
     steps {
       checkout scm
     }

  }


  //publish to npm repo
  stage('publish') {
     steps {
      sh 'env'
      sh 'npm publish'
     }

 }
     
 } 
}

